# General Information
name: "Project name"
status: "Desired Project Status - sandbox, graduated or archived"
brief_summary: "A one-sentence summary of the project"
website_link: "Link to website if applicable"
social_media_links: "Links to social media, if present, can be a list, or N/A if none"
project_usage_and_scale: "Brief summary of how widely the project is used e.g. list of companies"
why_join_chips: "Project's motivation to join CHIPS"
mission_statement_link: "Link to project's mission statement"
svg_logo_link: "Link to logo in .svg format, if present"
# The primary contact person for the project, will become TSC representative once admitted
primary_contact:
  name: "Contact's full name"
  email: "Contact's work email"
  github_handle: "Contact's GH handle, without the @"
  project_role: "Contact's role in the project"
# Contributor & Technical Information  
repositories: "Links to project repos - may be one or list of several in YAML list format"
issue_tracker_link: "Link to issue tracker"
active_committers: "Data about active project contributors"
release_methodology: "Information about project's release methodology and mechanics"
communication_channels: "List project communication channels e.g. Slack, IRC, Mailing Lists"
# Legal Information
license: "The project's open source license, normally Apache 2.0 unless special exception is granted"
financial_sponsorship: "Y/N - is there existing financial sponsorship of the project"
accepted_lf_code_of_conduct: "Y/N - will the project accept the LF Code of Conduct? See https://lfprojects.org/policies/code-of-conduct/"
adopted_chips_alliance_ip_policy: "Y/N - will the project adopt the CHIPS Alliance IP Policy? See https://technical-charter.chipsalliance.org"
chips_header_footer_text_on_website: "Y/N - will the project put links to CHIPS in the header or footer of its website? If no website, still answer 'yes' as declaration of will to do so."
trademarks_and_domains_transferred_to_lf: "Y/N - will the project transfer any registered trademarks and domains to CHIPS? If none are present, still answer 'yes' as declaration of intent if that should change."
security_vulnerabilities_reporting_process: "Describe briefly the project's security vulnerability reporting process, or just defer to https://github.com/chipsalliance/tsc#reporting-security-vulnerabilities"
spec_public_reference_implementation: "(For specifications only) link to reference implementation of the specification, N/A for non-spec projects"
