name: Check projects syntax

on:
  push:
    branches: ["main"]
  pull_request:
jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
    - name: Check
      run: |
        .github/check_projects_syntax.py projects/project-data-files/*yml
